var num2=2.1234;
var maxNum=Math.max(10,5,8,30);
var minNum=Math.min(10,5,8,30);
var roundNum=Math.round(num2);
var floorNum=Math.floor(num2);
var ceilNum=Math.ceil(num2);
var rndNum=Math.random();
var piNum=Math.PI;
document.write(maxNum,"<br>");
document.write(minNum,"<br>");
document.write(roundNum,"<br>");
document.write(floorNum,"<br>");
document.write(ceilNum,"<br>");
document.write(rndNum,"<br>");
document.write(piNum,"<br>");